pfe_admin_bibliotheque:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Bibliotheque:index" }

pfe_admin_bibliotheque_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Bibliotheque:show" }

pfe_admin_bibliotheque_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Bibliotheque:new" }

pfe_admin_bibliotheque_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Bibliotheque:create" }
    methods:  POST

pfe_admin_bibliotheque_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Bibliotheque:edit" }

pfe_admin_bibliotheque_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Bibliotheque:update" }
    methods:  [POST, PUT]

pfe_admin_bibliotheque_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Bibliotheque:delete" }
    methods:  [POST, DELETE]
