# default controller
pfe_dash_homepage:
    path:     /hello/{name}
    defaults: { _controller: PFEDashBundle:Default:index }

# bib controller
pfe_dash_bib_presentation:
    path:     /presentation/{id}
    defaults: { _controller: PFEDashBundle:Bib:presentation }

pfe_dash_bib_espaces:
    path:     /espaces/{id}
    defaults: { _controller: PFEDashBundle:Bib:espaces }

pfe_dash_bib_equipements:
    path:     /equipements/{id}
    defaults: { _controller: PFEDashBundle:Bib:equipements }

pfe_dash_bib_fonds:
    path:     /fonds/{id}
    defaults: { _controller: PFEDashBundle:Bib:fonds }

pfe_dash_bib_catalogues:
    path:     /catalogues/{id}
    defaults: { _controller: PFEDashBundle:Bib:catalogues }

pfe_dash_bib_prets:
    path:     /prets/{id}
    defaults: { _controller: PFEDashBundle:Bib:prets }

pfe_dash_bib_adherents:
    path:     /adherents/{id}
    defaults: { _controller: PFEDashBundle:Bib:adherents }

pfe_dash_bib_animations:
    path:     /animations/{id}
    defaults: { _controller: PFEDashBundle:Bib:animations }

pfe_dash_bib_remarques:
    path:     /remarques/{id}
    defaults: { _controller: PFEDashBundle:Bib:remarques }

pfe_dash_bib_menu:
    path:     /menu
    defaults: { _controller: PFEDashBundle:Bib:menu }

pfe_dash_bib_province:
    path:     /province/{id}
    defaults: { _controller: PFEDashBundle:Bib:province }

pfe_dash_bib_maj:
    path:     /maj
    defaults: { _controller: PFEDashBundle:Bib:maj }