pfe_saisi_equipement:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Equipement:index" }
    methods:  GET

saisi_equipe_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Equipement:show" }
    methods:  GET

saisi_equipe_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Equipement:new" }
    methods:  [GET, POST]

saisi_equipe_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Equipement:edit" }
    methods:  [GET, POST]

saisi_equipe_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Equipement:delete" }
    methods:  DELETE
