pfe_saisi_equipement:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Equipement:index" }

pfe_saisi_equipement_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Equipement:show" }

pfe_saisi_equipement_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Equipement:new" }

pfe_saisi_equipement_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Equipement:create" }
    methods:  POST

pfe_saisi_equipement_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Equipement:edit" }

pfe_saisi_equipement_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Equipement:update" }
    methods:  [POST, PUT]

pfe_saisi_equipement_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Equipement:delete" }
    methods:  [POST, DELETE]
