pfe_saisi_equipement:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Equipement:index" }
    methods:  GET

pfe_saisi_equipement_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Equipement:show" }
    methods:  GET

pfe_saisi_equipement_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Equipement:new" }
    methods:  [GET, POST]

pfe_saisi_equipement_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Equipement:edit" }
    methods:  [GET, POST]

pfe_saisi_equipement_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Equipement:delete" }
    methods:  DELETE
pfe_saisi_equipement_remove:
    path:     /{id}/remove
    defaults: { _controller: "PFEDashBundle:Equipement:remove" }
