pfe_saisi_espace:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Espace:index" }

pfe_saisi_espace_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Espace:show" }

pfe_saisi_espace_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Espace:new" }

pfe_saisi_espace_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Espace:create" }
    methods:  POST

pfe_saisi_espace_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Espace:edit" }

pfe_saisi_espace_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Espace:update" }
    methods:  [POST, PUT]

pfe_saisi_espace_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Espace:delete" }
    methods:  [POST, DELETE]
