pfe_saisi_pret:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Pret:index" }

pfe_saisi_pret_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Pret:show" }

pfe_saisi_pret_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Pret:new" }
    methods:  [GET, POST]

pfe_saisi_pret_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Pret:edit" }

pfe_saisi_pret_remove:
    path:     /{id}/remove
    defaults: { _controller: "PFEDashBundle:Pret:remove" }

pfe_saisi_pret_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Pret:delete" }
    methods:  [POST, DELETE]
