pfe_saisi_remarque:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Remarque:index" }

pfe_saisi_remarque_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Remarque:show" }

pfe_saisi_remarque_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Remarque:new" }

pfe_saisi_remarque_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Remarque:new" }
    methods:  POST

pfe_saisi_remarque_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Remarque:edit" }

pfe_saisi_remarque_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Remarque:update" }
    methods:  [POST, PUT]

pfe_saisi_remarque_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Remarque:delete" }
    methods:  [POST, DELETE]
    
pfe_saisi_remarque_remove:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Remarque:remove" }
