pfe_admin_socialmedia:
    path:     /list
    defaults: { _controller: "PFEDashBundle:SocialMedia:index" }

pfe_admin_socialmedia_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:SocialMedia:show" }

pfe_admin_socialmedia_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:SocialMedia:new" }

pfe_admin_socialmedia_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:SocialMedia:create" }
    methods:  POST

pfe_admin_socialmedia_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:SocialMedia:edit" }

pfe_admin_socialmedia_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:SocialMedia:update" }
    methods:  [POST, PUT]

pfe_admin_socialmedia_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:SocialMedia:delete" }
    methods:  [POST, DELETE,GET]
