pfe_tutelle_index:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Tutelle:index" }

pfe_tutelle_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Tutelle:delete" }

pfe_tutelle_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Tutelle:create" }

pfe_tutelle_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Tutelle:edit" }

pfe_tutelle_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Tutelle:show" }