tutelle_index:
    path:     /
    defaults: { _controller: "PFEDashBundle:Tutelle:index" }
    methods:  GET

tutelle_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Tutelle:show" }
    methods:  GET



