pfe_saisi_adherent:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Adherent:index" }
    methods:  GET
    
pfe_saisi_adherent_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Adherent:show" }

pfe_saisi_adherent_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Adherent:new" }

pfe_saisi_adherent_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Adherent:create" }
    methods:  POST

pfe_saisi_adherent_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Adherent:edit" }

pfe_saisi_adherent_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Adherent:update" }
    methods:  [POST, PUT]

pfe_saisi_adherent_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Adherent:delete" }
    methods:  [POST, DELETE]
