pfe_saisi_animation:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Animation:index" }

pfe_saisi_animation_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Animation:show" }

pfe_saisi_animation_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Animation:new" }

pfe_saisi_animation_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Animation:create" }
    methods:  POST

pfe_saisi_animation_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Animation:edit" }

pfe_saisi_animation_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Animation:update" }
    methods:  [POST, PUT]

pfe_saisi_animation_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Animation:delete" }
    methods:  [POST, DELETE]
