pfe_saisi_equipement:
    path:     /
    defaults: { _controller: "PFEDashBundle:Equipement:index" }
    methods:  GET

equipement_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Equipement:show" }
    methods:  GET

equipement_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Equipement:new" }
    methods:  [GET, POST]

equipement_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Equipement:edit" }
    methods:  [GET, POST]

equipement_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Equipement:delete" }
    methods:  DELETE
