pfe_saisi_internet:
    path:     /list
    defaults: { _controller: "PFEDashBundle:Internet:index" }

pfe_saisi_internet_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Internet:show" }

pfe_saisi_internet_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Internet:new" }

pfe_saisi_internet_create:
    path:     /create
    defaults: { _controller: "PFEDashBundle:Internet:create" }
    methods:  POST

pfe_saisi_internet_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Internet:edit" }

pfe_saisi_internet_update:
    path:     /{id}/update
    defaults: { _controller: "PFEDashBundle:Internet:update" }
    methods:  [POST, PUT]

pfe_saisi_internet_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Internet:delete" }
    methods:  [POST, DELETE]
