typeequipement_index:
    path:     /
    defaults: { _controller: "PFEDashBundle:Typeequipement:index" }
    methods:  GET

typeequipement_show:
    path:     /{id}/show
    defaults: { _controller: "PFEDashBundle:Typeequipement:show" }
    methods:  GET

typeequipement_new:
    path:     /new
    defaults: { _controller: "PFEDashBundle:Typeequipement:new" }
    methods:  [GET, POST]

typeequipement_edit:
    path:     /{id}/edit
    defaults: { _controller: "PFEDashBundle:Typeequipement:edit" }
    methods:  [GET, POST]

typeequipement_delete:
    path:     /{id}/delete
    defaults: { _controller: "PFEDashBundle:Typeequipement:delete" }
    methods:  DELETE
