<?php

namespace PFE\DashBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MiseajourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiseajourRepository extends EntityRepository
{
}
